### ISSUE TITLE
Wrong highlighting of quoted strings

### ISSUE THREAD

**Issue by Chris00** [ocaml/tuareg#89]
In code such as
```ocaml
let _ = {|\begin{array}{l|b}|}
let x = 1
```
the quoted string is highlighted fine.  However, if one introduces a newline after `{|` and then press TAB to indent it, so the end result is
```ocaml
let _ = {|
         \begin{array}{l|b}|}
let x = 1
```
then the end quoted string is not well detected well.  It is the modification that is the culprit, if I kill the buffer and reopen the file, the syntax highlighting is correct.

**Comment by monnier** [comment]
I  just pushed a patch which should fix this.

**Comment by Chris00** [comment]
Thanks.  However it does not completely fix the problem: in
```
let _ = {|
         \begin{array}{l|b}|}
```
the `l|b}|` stays uncolored after the TAB.  (This is the case even with emacs-25.1.50.1.)

**Comment by monnier** [comment]
Cannot reproduce this using the latest Tuareg from "master" and the latest Emacs from "master".

**Comment by Chris00** [comment]
Works for me too now.  Seems it was due to `elc` files that were not up to date :-(
